** **

** **

**Section 13 Acoustics**

** **

** **

** **

 

13.1 Abbreviations and Terminology

 

13.2 Velocities, Spectrum and Reference Levels

 

13.3 Pressure, Intensity

 

13.4 Weighting Curves

 

13.5 1/3 Octave Center Frequencies

 

13.6 References

 

**13.1 Abbreviations and Terminology**

** **

**Abbreviations**

*ANSI* American National Standards Institute

*dB* decibels

*f* frequency, cycles/sec

##### *Hz* Hertz

##### *nm* 10^-9^ meters

##### *P* sound power 

*p* pressure

*pW* 10^-12^ Watts

*x* RMS value of quantity

*x~o~* reference value of quantity

*μPa* 10^-6^ Pascals

** **

**Terminology**

decade band with the upper frequency x10 that of thelower.

decibels measure of a magnitude, *dB* = 10*log*~10~(mag).

far field beyond the near field (region where sound level drops -6 *dB* as distance from the source

doubles).

Hertz frequency in cycles/second.

narrow band band whose width is less than one-third octave but less than 1% of the center frequency near field range within a distance equal to the wavelength of the lowest frequency emitted or twice the greatest dimension of the subject.

octave a band with the upper freq exactly twice the lower freq. (common octaves include .0375-.075, .075-.15, 15-.3, .6-1.2, 1.2-2.4, 2.4-4.8, 4.8-9.6 k*Hz*).

pink noise has equal energy in each octave from 20 to 20,000 Hz, or with an energy content inversely

proportional to frequency.

random noise does not have a uniform frequency spectrum and has an amplitude, as a function of time, consis tent with a Gaussian distribution curve.

third-octave highest frequency =1.26 x lower frequency (ratio= 2^1/3^)

white noise has a constant spectrum level over the entire band of audible frequencies (need not be random).

 

**13.2 Acoustic Velocities, Spectrum, and Reference Levels**

** **

**Acoustic Velocity (speed of sound)**

** **

#####  [Medium]{.underline} [Approximate Velocity]{.underline}

Air (20° C) 343 m/s

Fresh water 1,480 m/s

Aluminum 5,150 m/s

#####  Concrete 3,600 m/s

Glass 5,300 m/s

Steel 6,000 m/s

 

**Wavelength** (λ) = [acoustic velocity]{.underline}

frequency

 

 

 

 

 

 

 

 

Human hearing range is approximately 20 to 20,000 *Hz*

• Ultrasound lies above 20,000 *Hz*

• Infrasound lies below 20 *Hz*

####  

#### Acoustic Reference Levels

[Quantity]{.underline} [Formula]{.underline}

Velocity (*L~v~*) 20log(*v/v~0~*) *v~o~* = 10 *nm/s^2^*

Intensity (*L~I~*) 10log(*I/I~0~*) *I~o~*= 1 *pW/m^2^*

Sound Power Level (*L~W~*) 10log(*P/P~0~*) *Po* = 1 *pW*

Sound Pressure Level "*SPL*" (*L~p~*) 20log(*p/p~0~*) 20*μPa* (air)

Pressure Spectrum Level (*PSL*)\* SPL -- 10*log∆f* (*dB*)

Pressure Band Level (*PBL*) *PSL* + 10*log∆f* (*dB*)

Overall SPL (*OASPL*) 10*log*~10~ Σ10^*SPL*/10^ 20 μ*Pa* (air)

 

\* the *SPL* contained within a band 1 *Hz* wide

 

 

 

 

 

 

 

 

 

 

 

 

**13.3 Acoustic Pressure and Intensity**

#### ** **Sound Pressure from Sound Power

 

Transmission Environment *L~p~*

Free Field *L~W~ + log Q -* 20 *log r -* 10.8 *dB*

Reflecting Plane *L~W~ + log Q -* 20 *log r -* 7.8 *dB*

Reverberant Room *L~W~ + log Q -* 20*l og R -* 6.2 *dB*

 

where *r* = distance from source

*Q* = directivity index of source

*R* = room constant

 

#### Acoustic Intensity

 

I - [Imaginary\[G~yx~(f)\]]{.underline} = [Im\[G~yx~(f)\]]{.underline}(for air)

4π*ρ~0~∆rf* 16.25 *∆rf*

 

where *ρ~0\ ~*= fluid density = 1.293 kg/m^3^ for air

*∆r* = microphone spacing (meters)

*f* = frequency

 

**Intensity Spectrum Level (ISL)**

 

Intensity level of a sound contained within a band 1*Hz* wide

\* *

*ISL* = 10 *log \_[I\_]{.underline}* = *IL* -- 10 *log∆f* (*dB*)

*I~o~∆f*

 

where *f* = center frequency of band

*I* = sound intensity (watts/*m*^2^)

*I~o~* = 10^-12^ watt/m^2^ reference intensity

*∆f* = bandwidth (*Hz*)

 

**13.4 Acoustic Weighting Curves** (ANSI S1.4 1983)

Weighting for SPL

 

Nominal Exact A B C

[Freq (*Hz*)]{.underline} [Freq (*Hz*)]{.underline} [(*dB*)]{.underline} [(*dB*)]{.underline} [(*dB*)]{.underline}

10 10.00 -70.4 -38.2 -14.3

12.5 12.59 -63.6 -33.3 -11.3

16 15.85 -56.4 -28.3 -8.4

20 19.95 -50.4 -24.2 -6.2

25 25.12 -44.8 -20.5 -4.4

31.5 31.62 -39.5 -17.1 -3.0

40 39.81 -34.5 -14.1 -2.0

50 50.12 -30.3 -11.6 -1.3

63 63.10 -26.2 -9.4 -0.8

80 79.43 -22.4 -7.3 -0.5

100 100.0 -19.1 -5.6 -0.3

125 126.9 -16.2 -4.2 -0.2

160 158.5 -13.2 -2.9 -0.1

200 199.5 -10.8 -2.0 .0

250 251.2 -8.7 -1.4 .0

315 316.2 -6.6 -0.9 .0

400 398.1 -4.8 -0.5 .0

500 501.2 -3.2 -0.3 .0

630 631.0 -1.9 -0.1 .0

800 794.3 -0.8 .0 .0

1,000 1,000 .0 .0 .0

1,250 1,259 0.6 .0 .0

1,600 1,585 1.0 .0 -0.1

2,000 1,995 1.2 -0.1 -0.2

2,500 2,512 1.3 -0.2 -0.3

3,150 3,162 1.2 -0.4 -0.5

4,000 3,981 1.0 -0.7 -0.8

5,000 5,012 0.6 -1.2 -1.3

6,300 6,310 -0.1 -1.9 -2.0

8,000 7,943 -1.1 -2.9 -3.0

10,000 10,000 -2.5 -4.3 -4.4

12,500 12,589 -4.3 -6.1 -6.2

16,000 15,849 -6.7 -8.5 -8.6

20,000 19,953 -9.3 -11.2 -11.3

 

**13.5 1/3 Octave Center Frequencies**

(ANSI S1.6 1984)

 

 Band Nominal Exact Octave

[No.]{.underline} [Center (*Hz*)]{.underline} [Center (*Hz*)]{.underline} [Center (*Hz*)]{.underline}

1 1.25 1.26

2 1.60 1.58

3 2.00 2.00 2.0

4 2.50 2.51

5 3.15 3.16

6 4.00 3.98 4.0

7 5.00 5.01

8 6.30 6.31

9 8.00 7.94 8.0

10 10.00 10.00

11 12.5 12.59

12 16.0 15.58 16.0

13 20.0 19.95

14 25.0 25.12

15 31.5 31.62 31.5

16 40.0 39.81

17 50.0 50.12

18 63.0 63.10 63.0

19 80.0 79.43

20 100.0 100.00

21 125.0 125.89 125.0

22 160.0 158.49

23 200.0 199.53

24 250.0 251.19 250.0

25 315.0 316.23

26 400.0 398.11

27 500.0 501.19 500.0

28 630.0 630.96

29 800.0 794.33

30 1,000 1,000.0 1,000

31 1,250 1,258.9

32  1,600 1,584.9

33 2,000 1,995.3 2,000

34 2,500 2,511.9

35 3,150 3,162.3

36 4,000 3,981.1 4,000

37 5,000 5,011.9

38 6,300 6,309.6

39 8,000 7,943.3 8,000

40 10,000 10,000.0

41 12,500 12,589.3

42 16,000 15,848.9 16,000

43 20,000 19,952.6

 

**13.6 References**

 

13.1 Beranek, Leo L., *Acoustic Measurements*, John Wiley & Sons, New York, New York, 1956.

 

13.2 Peterson, Arnold P.G. and Gross, Ervin E., Jr., *Handbook of Noise Measurement*, GenRag Incorporated, Concord, Massachusetts, 1978.

 

13.3 *Measuring Sound*, (Pamphlet), Bruel & Kjaer, Naerum, Denmark, September 1984.

 

13.4 *Pocket Handbook, Noise, Vibration, Light, Thermal Comfort*, Bruel & Kjaer, Naerum, Denmark, 1986.

 

####### Additional Reading 

 

Hunter, Joseph L., *Acoustics*, Prentice-Hall Incorporated, Englewood Cliffs, New Jersey, 1957.
