name: Render Handbook in HTML
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: R -e 'renv::restore()' #Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Render Book
        run: |
          cd ./handbookdown
          Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs/
